<!DOCTYPE html>
<?php require_once './config.php'; ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" type="text/css" href="css/main.css" >
        <title>Grupo Milla</title>
        <link rel="shortcut icon" href="./img/favicon.ico" />
        <script type="text/javascript" src="js/jquery-1.2.6.pack.js"></script>
        <script type="text/javascript" src="js/jquery.maskedinput-1.1.4.pack.js"></script>
        <script src="js/cpfxcnpj.js" type="text/javascript"></script>
    </head>
    <body>
        <div id="wrapper">
            <header>
                <table class="headerTable">
                    <thead>
                        <tr>
                            <td><img src="img/logomilla.png" alt="Lojas Milla Logomarca" class="logoimg"></td>
                            <td><img src="img/logonm.png" alt="Lojas Milla Logomarca" class="logoimg"></td>
                        </tr>
                    </thead>
                </table>
            </header>
            <main>
