<tfoot>
    <tr>
        <th colspan="2">Total Titulos</th>
        <td colspan="1"><?php echo 'R$ ' . number_format($cliente->totalTitulos, 2, ',', '.'); ?></td>
    </tr>
</tfoot>
</tbody>
</table>
<div>
    <button id="anterior" disabled>&lsaquo; Anterior</button>
    <span id="numeracao"></span>
    <button id="proximo" disabled>Próximo &rsaquo;</button>
</div>
<h1>* Títulos com mais de 60 dias de atraso, ligar para Cobrança <?php echo FONE_COBRANCA; ?></h1>
