<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of testePHPClass
 *
 * @author julia
 */
class testePHPClass {

    private $ConsultaTitulosCPF;
    private $pdfboleto;

    function getConsultaTitulosCPF() {
        return $this->ConsultaTitulosCPF;
    }

    function getPdfboleto() {
        return $this->pdfboleto;
    }

    public function __construct() {
        $this->pdfboleto = '';

        $this->ConsultaTitulosCPF = '[
            {
        "ID": "1-1-1007944899-81767799-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767799,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "21/03/2020",
        "DtVencimento": "23/03/2020",
        "Dias_Atrazo": 10,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 69.9,
        "VlrSaldo": 69.9,
        "VlrJuro": 3.94,
        "VlrMulta": 1.4,
        "VlrCorrigido": 75.24,
        "VlrAbatimento": 0,
        "VlrLiquido": 75.24,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "10499.01190 15599.063284 70000.003650 1 82120000006990",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767799-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767799,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "21/03/2020",
        "DtVencimento": "23/03/2020",
        "Dias_Atrazo": 10,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 69.9,
        "VlrSaldo": 69.9,
        "VlrJuro": 3.94,
        "VlrMulta": 1.4,
        "VlrCorrigido": 75.24,
        "VlrAbatimento": 0,
        "VlrLiquido": 75.24,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "10499.01190 15599.063284 70000.003650 1 82120000006990",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767799-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767799,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "21/03/2020",
        "DtVencimento": "23/03/2020",
        "Dias_Atrazo": 10,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 69.9,
        "VlrSaldo": 69.9,
        "VlrJuro": 3.94,
        "VlrMulta": 1.4,
        "VlrCorrigido": 75.24,
        "VlrAbatimento": 0,
        "VlrLiquido": 75.24,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "10499.01190 15599.063284 70000.003650 1 82120000006990",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767799-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767799,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "21/03/2020",
        "DtVencimento": "23/03/2020",
        "Dias_Atrazo": 10,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 69.9,
        "VlrSaldo": 69.9,
        "VlrJuro": 3.94,
        "VlrMulta": 1.4,
        "VlrCorrigido": 75.24,
        "VlrAbatimento": 0,
        "VlrLiquido": 75.24,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "10499.01190 15599.063284 70000.003650 1 82120000006990",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    },
    {
        "ID": "1-1-1007944899-81767599-1",
        "Cliente": 1007944899,
        "Nome_Cliente": "ROGERIO BORDIGNON",
        "Filial": 1,
        "NrTitulo": 81767599,
        "Parcela": 1,
        "TotalParcela": 1,
        "DtEmissao": "25/03/2020",
        "DtVencimento": "24/04/2020",
        "Dias_Atrazo": 0,
        "Descricao_FlgStatus": "Pendente",
        "Descricao_Origem": "CARTEIRA BOLETO",
        "Descricao_modalidade": "Boleto Bancario",
        "VlrTitulo": 48,
        "VlrSaldo": 48,
        "VlrJuro": 0,
        "VlrMulta": 0,
        "VlrCorrigido": 48,
        "VlrAbatimento": 0,
        "VlrLiquido": 48,
        "VlrTaxaCobranca": 0,
        "TaxaDescontoAdimplencia": 0,
        "VlrDesconto_Adimplencia": 0,
        "FlgPermiteNegociacao": "N",
        "NrNotaFiscal": "null",
        "ModeloNotaFiscal": "null",
        "SerieNotaFiscal": "null",
        "ChaveNota": "null",
        "Linha_Digitavel": "null",
        "FlgPermiteEmissaoBoleto": "S",
        "Portador": 1,
        "Descricao_Portador": "Loja 01"
    } ]';
    }

}
